apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: telemetry-connect-default
  namespace: default
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: telemetry-cluster-kafka-bootstrap.default.svc.cluster.local:9092
  image: my-kafka-connect:v1
  
  groupId: connect-cluster-default
  offsetStorageTopic: connect-cluster-offsets-default
  configStorageTopic: connect-cluster-configs-default
  statusStorageTopic: connect-cluster-status-default
  
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
