apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: raw-telemetry
  namespace: default
  labels:
    strimzi.io/cluster: telemetry-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: processed-events
  namespace: default
  labels:
    strimzi.io/cluster: telemetry-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
