{{- if .Values.keycloak.enabled }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.keycloak.replicas }}
  
  bootstrapAdmin:
    user:
      secret: keycloak-admin-credentials
  
  db:
    vendor: postgres
    host: {{ .Values.keycloak.database.host }}
    port: {{ .Values.keycloak.database.port }}
    database: {{ .Values.keycloak.database.database }}
    usernameSecret:
      name: {{ .Values.keycloak.database.existingSecret }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.database.existingSecret }}
      key: {{ .Values.keycloak.database.existingSecretKey }}
  
  http:
    httpEnabled: true

  proxy:
    headers: xforwarded

  ingress:
    enabled: false

  {{- if .Values.keycloak.ingress.hostname }}
  hostname:
    hostname: {{ .Values.keycloak.ingress.hostname }}
  {{- end }}
{{- end }}
