apiVersion: v2
name: postgres
description: A Helm chart for Shared PostgreSQL
type: application
version: 0.1.0
appVersion: "15.3"
dependencies:
  - name: postgres
    version: 0.13.8
    repository: "oci://registry-1.docker.io/cloudpirates"
