apiVersion: v2
name: cert-manager
description: cert-manager with Let's Encrypt ClusterIssuers for TLS certificate management
version: 1.0.0
appVersion: "1.13.3"

dependencies:
  - name: cert-manager
    version: v1.13.3
    repository: https://charts.jetstack.io
