apiVersion: v2
name: ingress-nginx
description: NGINX Ingress Controller for GKE with static IP support
version: 1.0.0
appVersion: "1.9.0"

dependencies:
  - name: ingress-nginx
    version: 4.9.0
    repository: https://kubernetes.github.io/ingress-nginx
