{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iot-load-tester.serviceAccountName" . }}
  labels:
    {{- include "iot-load-tester.labels" . | nindent 4 }}
{{- end }}
