apiVersion: v2
name: postgres-operator
description: Zalando Postgres Operator for Kubernetes
version: 1.0.0
appVersion: "1.13.0"

keywords:
  - postgresql
  - postgres
  - database
  - operator

maintainers:
  - name: Infrastructure Team

dependencies:
  - name: postgres-operator
    version: "1.13.0"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
