apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
    {{- include "artemis.labels.standard" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "artemis.name" . }}
      release: {{ .Release.Name | quote }}
