apiVersion: v1
kind: Secret
metadata:
  name: {{ include "producer.fullname" . }}-secrets
  labels:
    {{- include "producer.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}
