apiVersion: v2
name: oauth2-proxy
description: A Helm chart for OAuth2 Proxy
type: application
version: 1.0.0
appVersion: 7.5.1
dependencies:
  - name: oauth2-proxy
    version: 6.2.0
    repository: https://oauth2-proxy.github.io/manifests
